apiVersion: v1
kind: Secret
metadata:
  name: user-at-github
  annotations:
    tekton.dev/git-0: https://github.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: <replace-with-github.com-shortname-userid>
  password: <replace-with-github.com-personal-access-token>