apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: python-django-app-ocp-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/jedward19/python-django-app-ocp.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: python-django-app-ocp-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/dev-jce/python-django-app-ocp:latest
